# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=100)),
                ('content_author', models.CharField(max_length=100)),
                ('content_content', models.TextField()),
                ('content_read', models.IntegerField()),
                ('content_create_date', models.DateTimeField()),
            ],
        ),
    ]
